language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
        
before_script:
  - composer --dev install

script:
  - mkdir -p build/logs
  - phpunit
  
after_script:
  - php vendor/bin/coveralls -v
